[package]
name = "myscheme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
once_cell = "1.17.1"
regex = "1.6.0"

[dependencies.uuid]
version = "1.3.1"
features = ["v4", "fast-rng", "macro-diagnostics"]

[dev-dependencies]
assert_fs = "1.0.13"
